from . import res_company
from . import res_config_setting
from . import affinda_organization
from . import affinda_workspace
from . import affinda_workspace_collection
from . import affinda_document
from . import res_partner
from . import account_move
from . import hr_expense